[2024-04-09T16:51:34.979+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: fruits_dag.create_fruits_table scheduled__2023-03-12T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
[2024-04-09T17:25:50.880+0000] {task_context_logger.py:104} ERROR - Detected zombie job: {'full_filepath': '/opt/airflow/dags/fruit_table_dag.py', 'processor_subdir': '/opt/airflow/dags', 'msg': "{'DAG Id': 'fruits_dag', 'Task Id': 'create_fruits_table', 'Run Id': 'scheduled__2023-03-12T00:00:00+00:00', 'Hostname': 'fd38698150f5', 'External Executor Id': 'fbf158dc-ea30-403c-8c44-50868204a450'}", 'simple_task_instance': <airflow.models.taskinstance.SimpleTaskInstance object at 0x7fb54b612420>, 'is_failure_callback': True} (See https://airflow.apache.org/docs/apache-airflow/stable/core-concepts/tasks.html#zombie-undead-tasks)
[2024-04-09T17:26:01.668+0000] {task_context_logger.py:104} ERROR - Detected zombie job: {'full_filepath': '/opt/airflow/dags/fruit_table_dag.py', 'processor_subdir': '/opt/airflow/dags', 'msg': "{'DAG Id': 'fruits_dag', 'Task Id': 'create_fruits_table', 'Run Id': 'scheduled__2023-03-12T00:00:00+00:00', 'Hostname': 'fd38698150f5', 'External Executor Id': 'fbf158dc-ea30-403c-8c44-50868204a450'}", 'simple_task_instance': <airflow.models.taskinstance.SimpleTaskInstance object at 0x7fb54b962180>, 'is_failure_callback': True} (See https://airflow.apache.org/docs/apache-airflow/stable/core-concepts/tasks.html#zombie-undead-tasks)
