[2024-04-09T18:49:49.000+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-09T18:49:49.923+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fruits_dag.insert_fruit_data scheduled__2023-03-09T00:00:00+00:00 [queued]>
[2024-04-09T18:49:50.149+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fruits_dag.insert_fruit_data scheduled__2023-03-09T00:00:00+00:00 [queued]>
[2024-04-09T18:49:50.167+0000] {taskinstance.py:2303} INFO - Starting attempt 2 of 3
[2024-04-09T18:49:50.545+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): insert_fruit_data> on 2023-03-09 00:00:00+00:00
[2024-04-09T18:49:50.850+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2480) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-09T18:49:50.857+0000] {standard_task_runner.py:63} INFO - Started process 2503 to run task
[2024-04-09T18:49:50.872+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'fruits_dag', 'insert_fruit_data', 'scheduled__2023-03-09T00:00:00+00:00', '--job-id', '250', '--raw', '--subdir', 'DAGS_FOLDER/fruit_table_dag.py', '--cfg-path', '/tmp/tmpez4se3re']
[2024-04-09T18:49:50.915+0000] {standard_task_runner.py:91} INFO - Job 250: Subtask insert_fruit_data
[2024-04-09T18:49:51.192+0000] {task_command.py:426} INFO - Running <TaskInstance: fruits_dag.insert_fruit_data scheduled__2023-03-09T00:00:00+00:00 [running]> on host fd38698150f5
[2024-04-09T18:49:53.322+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fruits_dag' AIRFLOW_CTX_TASK_ID='insert_fruit_data' AIRFLOW_CTX_EXECUTION_DATE='2023-03-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-03-09T00:00:00+00:00'
[2024-04-09T18:49:53.341+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-09T18:49:53.608+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-09T18:49:53.688+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/fruit_table_dag.py", line 12, in insert_fruit_data_into_db
    conn = Variable.get('eskplorasi_postgres')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable eskplorasi_postgres does not exist'
[2024-04-09T18:49:54.097+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=fruits_dag, task_id=insert_fruit_data, execution_date=20230309T000000, start_date=20240409T184949, end_date=20240409T184954
[2024-04-09T18:49:54.196+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 250 for task insert_fruit_data ('Variable eskplorasi_postgres does not exist'; 2503)
[2024-04-09T18:49:54.397+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-09T18:49:54.622+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-09T18:49:54.653+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-04-09T19:58:01.166+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-09T19:58:02.026+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fruits_dag.insert_fruit_data scheduled__2023-03-09T00:00:00+00:00 [queued]>
[2024-04-09T19:58:02.642+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fruits_dag.insert_fruit_data scheduled__2023-03-09T00:00:00+00:00 [queued]>
[2024-04-09T19:58:02.715+0000] {taskinstance.py:2303} INFO - Starting attempt 2 of 2
[2024-04-09T19:58:03.658+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): insert_fruit_data> on 2023-03-09 00:00:00+00:00
[2024-04-09T19:58:03.738+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=429) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-09T19:58:03.811+0000] {standard_task_runner.py:63} INFO - Started process 459 to run task
[2024-04-09T19:58:03.768+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'fruits_dag', 'insert_fruit_data', 'scheduled__2023-03-09T00:00:00+00:00', '--job-id', '473', '--raw', '--subdir', 'DAGS_FOLDER/fruit_table_dag.py', '--cfg-path', '/tmp/tmpo7mtms6w']
[2024-04-09T19:58:03.881+0000] {standard_task_runner.py:91} INFO - Job 473: Subtask insert_fruit_data
[2024-04-09T19:58:04.721+0000] {task_command.py:426} INFO - Running <TaskInstance: fruits_dag.insert_fruit_data scheduled__2023-03-09T00:00:00+00:00 [running]> on host a89a4f7de6ef
[2024-04-09T19:58:05.658+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fruits_dag' AIRFLOW_CTX_TASK_ID='insert_fruit_data' AIRFLOW_CTX_EXECUTION_DATE='2023-03-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-03-09T00:00:00+00:00'
[2024-04-09T19:58:05.680+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-09T19:58:05.988+0000] {base.py:84} INFO - Using connection ID 'eksplorasi_postgres' for task execution.
[2024-04-09T19:58:06.433+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-04-09T19:58:06.455+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-09T19:58:06.590+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=fruits_dag, task_id=insert_fruit_data, execution_date=20230309T000000, start_date=20240409T195802, end_date=20240409T195806
[2024-04-09T19:58:07.475+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-09T19:58:07.707+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-09T19:58:07.801+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
