[2024-04-17T22:51:28.577+0700] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-17T22:51:28.598+0700] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_analysis_workflow_dag.transform_data scheduled__2024-04-16T00:00:00+00:00 [queued]>
[2024-04-17T22:51:28.605+0700] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_analysis_workflow_dag.transform_data scheduled__2024-04-16T00:00:00+00:00 [queued]>
[2024-04-17T22:51:28.606+0700] {taskinstance.py:2303} INFO - Starting attempt 1 of 4
[2024-04-17T22:51:28.628+0700] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): transform_data> on 2024-04-16 00:00:00+00:00
[2024-04-17T22:51:28.633+0700] {standard_task_runner.py:63} INFO - Started process 7165 to run task
[2024-04-17T22:51:28.635+0700] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'data_analysis_workflow_dag', 'transform_data', 'scheduled__2024-04-16T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/Soal_Eksplorasi.py', '--cfg-path', '/tmp/tmphhox52dq']
[2024-04-17T22:51:28.636+0700] {standard_task_runner.py:91} INFO - Job 4: Subtask transform_data
[2024-04-17T22:51:28.678+0700] {task_command.py:426} INFO - Running <TaskInstance: data_analysis_workflow_dag.transform_data scheduled__2024-04-16T00:00:00+00:00 [running]> on host LAPTOP-984VLCTV.
[2024-04-17T22:51:28.747+0700] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='nuri' AIRFLOW_CTX_DAG_ID='data_analysis_workflow_dag' AIRFLOW_CTX_TASK_ID='transform_data' AIRFLOW_CTX_EXECUTION_DATE='2024-04-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-16T00:00:00+00:00'
[2024-04-17T22:51:28.748+0700] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-17T22:51:28.759+0700] {logging_mixin.py:188} WARNING - /home/newrey/airflow/dags/Soal_Eksplorasi.py:38 FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.
[2024-04-17T22:51:28.766+0700] {python.py:237} INFO - Done. Returned value was: None
[2024-04-17T22:51:28.767+0700] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-17T22:51:28.772+0700] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=data_analysis_workflow_dag, task_id=transform_data, execution_date=20240416T000000, start_date=20240417T155128, end_date=20240417T155128
[2024-04-17T22:51:28.808+0700] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-17T22:51:28.831+0700] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-04-17T22:51:28.835+0700] {local_task_job_runner.py:222} INFO - ::endgroup::
