[2024-04-09T17:54:43.331+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-09T17:54:43.513+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fruits_dag.create_fruits_table scheduled__2023-03-03T00:00:00+00:00 [queued]>
[2024-04-09T17:54:43.551+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fruits_dag.create_fruits_table scheduled__2023-03-03T00:00:00+00:00 [queued]>
[2024-04-09T17:54:43.557+0000] {taskinstance.py:2303} INFO - Starting attempt 6 of 6
[2024-04-09T17:54:43.804+0000] {taskinstance.py:2327} INFO - Executing <Task(PostgresOperator): create_fruits_table> on 2023-03-03 00:00:00+00:00
[2024-04-09T17:54:43.851+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1247) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-09T17:54:43.861+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'fruits_dag', 'create_fruits_table', 'scheduled__2023-03-03T00:00:00+00:00', '--job-id', '62', '--raw', '--subdir', 'DAGS_FOLDER/fruit_table_dag.py', '--cfg-path', '/tmp/tmphbvrdbh4']
[2024-04-09T17:54:43.874+0000] {standard_task_runner.py:91} INFO - Job 62: Subtask create_fruits_table
[2024-04-09T17:54:43.865+0000] {standard_task_runner.py:63} INFO - Started process 1286 to run task
[2024-04-09T17:54:44.078+0000] {task_command.py:426} INFO - Running <TaskInstance: fruits_dag.create_fruits_table scheduled__2023-03-03T00:00:00+00:00 [running]> on host fd38698150f5
[2024-04-09T17:54:44.680+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fruits_dag' AIRFLOW_CTX_TASK_ID='create_fruits_table' AIRFLOW_CTX_EXECUTION_DATE='2023-03-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='6' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-03-03T00:00:00+00:00'
[2024-04-09T17:54:44.683+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-09T17:54:44.684+0000] {sql.py:276} INFO - Executing: 
        CREATE TABLE IF NOT EXISTS fruits (
            id SERIAL PRIMARY KEY,
            name VARCHAR(50) NOT NULL,
            family VARCHAR(50) NOT NULL,
            type VARCHAR(50) NOT NULL,
            color VARCHAR(50) NOT NULL
        );
    
[2024-04-09T17:54:44.709+0000] {base.py:84} INFO - Using connection ID 'postgres_eksplorasi' for task execution.
[2024-04-09T17:54:44.733+0000] {base.py:84} INFO - Using connection ID 'postgres_eksplorasi' for task execution.
[2024-04-09T17:54:44.740+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-09T17:54:44.741+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 397, in run
    with closing(self.get_conn()) as conn:
                 ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/hooks/postgres.py", line 161, in get_conn
    self.conn = psycopg2.connect(**conn_args)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: connection to server at "postgres" (172.20.0.3), port 5432 failed: fe_sendauth: no password supplied

[2024-04-09T17:54:44.758+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=fruits_dag, task_id=create_fruits_table, execution_date=20230303T000000, start_date=20240409T175443, end_date=20240409T175444
[2024-04-09T17:54:44.790+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 62 for task create_fruits_table (connection to server at "postgres" (172.20.0.3), port 5432 failed: fe_sendauth: no password supplied
; 1286)
[2024-04-09T17:54:44.856+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-09T17:54:44.884+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1296: AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
  result = cls.__new__(cls)

[2024-04-09T17:54:44.924+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-09T17:54:44.933+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
